set_property(GLOBAL PROPERTY KERNEL_GET_TYPE "")
set_property(GLOBAL PROPERTY KERNEL_GET_TYPE_ZIP_FILE "")
set_property(GLOBAL PROPERTY KERNEL_GET_TYPE_GIT_REPOSITORY "")
set_property(GLOBAL PROPERTY KERNEL_GET_TYPE_GIT_TAG "")

set(PLATFORM_FEATURES)
list(APPEND PLATFORM_FEATURES "feature1")
set_property(GLOBAL PROPERTY PLATFORM_FEATURES ${PLATFORM_FEATURES})
