include(PlatformDefault.cmake)

set_property(GLOBAL PROPERTY KERNEL_GET_TYPE "ZIP")
set_property(GLOBAL PROPERTY KERNEL_GET_TYPE_ZIP_FILE "~/Downloads/linux-5.15.zip")
#set_property(GLOBAL PROPERTY KERNEL_GET_TYPE "GIT")
#set_property(GLOBAL PROPERTY KERNEL_GET_TYPE_GIT_REPOSITORY "git@github.com:torvalds/linux.git")
#set_property(GLOBAL PROPERTY KERNEL_GET_TYPE_GIT_TAG "v5.15")

get_property(PLATFORM_FEATURES GLOBAL PROPERTY PLATFORM_FEATURES)
list(APPEND PLATFORM_FEATURES "feature2")
set_property(GLOBAL PROPERTY PLATFORM_FEATURES ${PLATFORM_FEATURES})
